sonar.projectKey=code-hallucination-result-v2
sonar.projectName=Code hallucination result
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
sonar.python.version=3.11
sonar.java.source=17
sonar.java.binaries=classes
sonar.issue.ignore.multicriteria=wrapper1,wrapper2,wrapper3,wrapper4
sonar.issue.ignore.multicriteria.wrapper1.ruleKey=java:S1220
sonar.issue.ignore.multicriteria.wrapper1.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.wrapper2.ruleKey=java:S101
sonar.issue.ignore.multicriteria.wrapper2.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.wrapper3.ruleKey=java:S1118
sonar.issue.ignore.multicriteria.wrapper3.resourceKey=**/*.java
sonar.issue.ignore.multicriteria.wrapper4.ruleKey=java:S1598
sonar.issue.ignore.multicriteria.wrapper4.resourceKey=**/*.java
